### ISSUE TITLE
Get Iteration 1 complete

### ISSUE THREAD

**Issue by ericadamski** [ZEP-Arter/KNT#10]
Before we can really start on the next part of this project we need to get Movement and Combat working, so that is what branch "Iteration_two" is, I will start to work on networking as well in this branch but once we have Iteration_one complete then we will do another merge to the master.

WOO! On our way.

**Comment by ericadmski** [comment]
This is still not complete! We only have 2 weeks left!! 

BETTER GET ON YOUR SHIT!
