### ISSUE TITLE
Integrate Networking

### ISSUE THREAD

**Issue by ericadmski** [ZEP-Arter/KNT#11]
This will need a large rework of the way the GUI is organized. I will lead the transformation and integrate the Networking independent of the continuation of complete the other issue #10 !!

@ZEP-Arter do all phases and introduce characters
@BBKING55 we will ask you when we need something from the UI, and you need to be read! Until then, get some basic pop-up windows working ( especially one with the ability to enter text )
~~@ericadamski Complete networking + integrate/code clean-up reorganize~~

**Comment by ericadamski** [comment]
Not doing this, not enough time.
