### ISSUE TITLE
Workflow weekly assignments

### ISSUE THREAD

**Issue by ericadmski** [ZEP-Arter/KNT#2]
@ericadamski : ~~doing player class, character class,~~ movement class, networking

`IMPORTANT : @ZEP-Arter : @ericadamski we need to get together sometime either this weekend 
or this week after wednesday and have a HUGE code session, we haven't really tested any of our stuff 
so we really need to get on it!!` 

@ZEP-Arter : ~~doing tile class, things class,~~ combat class (combat need exe)

@BBKING55 needs to get a UI working.

**Comment by ZEP-Arter** [comment]
Currently working on Tile class first.

**Comment by ericadmski** [comment]
I have started to put things together, we really need to have a day where we code together!!! I have made template-ish things for the player class and the Character class. Still lots of stuff to do, I haven't started networkng yet... but we need to get this shit going if we want it ready  in two weeks. WOOT

**Comment by ericadamski** [comment]
Movement and Networking have to wait until an executable has become available.

**Comment by ZEP-Arter** [comment]
I am going to close this issue and create a new one with stuff in more detail
