### ISSUE TITLE
Sign-Up!

### ISSUE THREAD

**Issue by ericadamski** [ZEP-Arter/KNT#7]
https://code.stypi.com - its like google docs but for code, it seems useful when we are on skype ( especcially tomorrow ! ) <- underline this!!! =P

**Comment by ericadamski** [comment]
BTW ITS FREE

**Comment by ericadamski** [comment]
Please let me know when you join.

**Comment by ZEP-Arter** [comment]
I have signed up. @BBKING55 once you sign up comment and close. :)

**Comment by brandenbortolin** [comment]
Signed up.
